# Copyright 2024 Weavers @ Eternal Loom. All rights reserved.
#
# Use of this software is governed by the license that can be
# found in LICENSE file in the source repository.

name: Coverage

on:
    workflow_run:
        workflows: [CI]
        types: [completed]

permissions:
    statuses: write
    contents: write

jobs:
    smokeshow:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest

        steps:
            - uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - run: pip install smokeshow

            - uses: dawidd6/action-download-artifact@v6
              with:
                workflow: ci.yml
                github_token: ${{ secrets.ACTION_TOKEN }}
                commit: ${{ github.event.workflow_run.head_sha }}
                allow_forks: true

            - run: smokeshow upload coverage-html
              env:
                SMOKESHOW_GITHUB_STATUS_DESCRIPTION: Coverage {coverage-percentage}
                SMOKESHOW_GITHUB_COVERAGE_THRESHOLD: 95
                SMOKESHOW_GITHUB_CONTEXT: coverage
                SMOKESHOW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SMOKESHOW_GITHUB_PR_HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
                SMOKESHOW_AUTH_KEY: ${{ secrets.SMOKESHOW_AUTH_KEY }}
